//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRUD
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class tbl_Countries
    {
        public tbl_Countries()
        {
            this.tbl_Contacts = new HashSet<tbl_Contacts>();
        }
    
        public int countryId { get; set; }

        [DisplayName("Country")]
        public string countryName { get; set; }
    
        public virtual ICollection<tbl_Contacts> tbl_Contacts { get; set; }
    }
}
